project:
  type: website
  output-dir: docs
  resources:
    - files/**
    - .nojekyll

website:
  title: "Viktor Jahnke"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Talks
      - href: cv.qmd
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



